Repository defenseunicorns/uds-security-hub, pull requests merged in 2024-09, with the labels that each got.

#241 add test cases for type/scan.go
  pkg/types/scan_test.go
Labels: testing

#234 add test cases for semver/semver.go
  pkg/semver/semver.go
  pkg/semver/semver_test.go
Labels: testing

#246 docs: Add detailed release instructions
  docs/release.md
Labels: documentation

#248 add test cases for pkg/scan/trivvy_scannable.go
  pkg/scan/trivy_scannable_test.go
Labels: testing

#250 add test case for internal/oci/oci.go
  internal/oci/oci_test.go
Labels: testing

#254 add test cases for internal/github/github.go
  internal/github/github_test.go
Labels: testing

#249 add test cases for internal/sql/connection.go
  internal/sql/e2e_test.go
Labels: testing

#253 add endpoint to apko.yaml
  .github/workflows/apko.yaml
Labels: bug, github_actions

#270 chore(lint/ci): simplify configuration per gocritic
  .golangci.yaml
Labels: red-diff

#271 fix leapfrog scan workflow
  .github/workflows/leapfrog-scan.yaml
Labels: bug

#266 add test case for pkg/types/http.go
  pkg/types/http_test.go
Labels: testing

#265 add test case for internal/data/db/report.go
  internal/data/db/report_test.go
Labels: testing

#267 chore(logging): replace zap with log/slog
  cmd/scan.go
  cmd/store/main.go
  cmd/store/main_test.go
  codecov.yml
  go.mod
  go.sum
  internal/data/db/scan.go
  internal/data/db/scan_test.go
  internal/log/zap..go
  internal/log/zap_test.go
  pkg/scan/e2e_test.go
  pkg/scan/local_scan.go
  pkg/scan/local_scan_test.go
  pkg/scan/remote_scanner.go
  pkg/scan/remote_scanner_test.go
  pkg/scan/scan_factory.go
  pkg/scan/scan_factory_test.go
  pkg/types/log.go
  pkg/types/mock_log.go
  pkg/types/scan.go
Labels: red-diff

#284 add test case for pkg/scan/scan_result_reader.go
  pkg/scan/scan_result_reader_test.go
Labels: testing

#288 add test cases for pkg/scan/sbom.go
  pkg/scan/sbom_test.go
Labels: testing

#289 add test cases for internal/data/model/package.go
  internal/data/model/package_test.go
Labels: testing

#290 add test cases for pkg/scan/local_scan.go
  pkg/scan/local_scan_test.go
Labels: testing

#293 add test cases for internal/data/model/vulnerability.go
  internal/data/model/vulnerability_test.go
  internal/data/model/vulnerabilty_test.go
Labels: testing

#296 add test cases for pkg/scan/rootfs.go
  pkg/scan/rootfs_test.go
Labels: testing

#298 add test cases for internal/github/github.go
  internal/github/github_test.go
Labels: testing

#291 add test cases for internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
Labels: testing
